### ISSUE TITLE
Set Up Kanban Board - Final Capstone Project || Futuristic Transportation

### ISSUE THREAD

**Issue by Luiscarlosvd** [Luiscarlosvd/futuristic-transportation#16]
**Futuristic Transportation:** 
[**_Link to Github Project._**](https://github.com/users/Luiscarlosvd/projects/2/views/1)

We are 4 members in our team: @Luiscarlosvd, @Alejuda, @mrcbq and @enmanuelbayen.

![image](https://github.com/Luiscarlosvd/futuristic-transportation/assets/99110717/04aefd81-fa1d-439a-8af6-4b714b9de26e)

**Comment by Meltrust** [comment]
Hi @Luiscarlosvd 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have been assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] According to the project requirements:

![image](https://github.com/Luiscarlosvd/futuristic-transportation/assets/57421823/78c703a2-0c0f-4d2b-b7dc-c2d3f58e4714)

Nevertheless, some tasks do not have descriptions, like this one:

![image](https://github.com/Luiscarlosvd/futuristic-transportation/assets/57421823/861e5aa6-a91e-4d92-877c-e783b647ee0a)

Therefore, kindly, ensure all tasks have descriptions in order to meet this particular [requirement](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md).

- [ ] Also, according to the project requirements:

![image](https://github.com/Luiscarlosvd/futuristic-transportation/assets/57421823/aede2c2a-5151-4795-ba86-3b219c942b3c)

At the time of this review, these are the pointings:

@mrcbq 27
@Luiscarlosvd 21
@enmanuelbayen 28
@Alejuda 21

As you can see, @Luiscarlosvd and @Alejuda have too few points as compared to @mrcbq and @enmanuelbayen.  The rule is that no team member may have more than 5 points than any other.  Therefore, the limit is 5 points difference.

Kindly, make it so all members have less than 5 points difference as compared to each other.

That way, we will meet this other particular [requirement](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md).

_tip:  Play with the numbers and/or reassign tasks in order to meet the spec._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Luiscarlosvd** [comment]
- Add description for all the cards. ✔️ 
- All members have less than 5 points difference as compared to each other. ✔️

**Comment by Meltrust** [comment]
Hi @Luiscarlosvd,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards now have descriptions, and the pointings are equal according to the spec✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
